language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: friends-quotes-api
  skip_cleanup: true
  api_key:
    secure: EHtAoY42aYvrc4lnsi0lna0VbBd+HjfsW/voGUK6cqF6V13GQ4LcD7Mh/Sqjb4vhi9aimUdqNOxti70Xh3+YWPrL7y+wE2pWdXNEt6iq3ugdui1G9PWD72Li/1qdBjOEzjAYQVhFIdJOyFLUkqOURrJiGZoiutSiACjkWv3kWYSeryHOehB2mHqZLhbpKaikmFLr1ryirwPV0OrvrWKATGjjI9xYAKVMuXUNKRXHOxI5QWrh617e3T8vB/Hqm5VOYuYU4CeaqR5VGVdZT8rFSNd7ucXFgrkwliv0k7VdFbn/DldYt2kQZws2BuRTkUO1RxthXLEMZ2BeRzttZqu72884BeLPH2phKyDXiLbPQIGrmd9eM/HIwKsLcNbCEVWgsgX5SPLwq6GNdXDIR5OHOlHkKMc51EUeCY1dONlbzwyo49urXgNFzhJSz9IMADACc0iYTM+vRosUpX1y/3Z9LIxKdSTJLuLtmCzGe55ic5Vz4elkCK1ZaFub964qhaTQaEpROmWZY0YLB4BPWs6pAPvjSB/cFUDaiN/0aKIKE8cuQzMJVu65h7jRlz5+sctn5h+yRvyq+MiVjRQaDx/e+UwazxkkYOFzj8R2xZCtTT6Ci3aAAx2cC0FBDi+R6Gyx9ovRFjXVQ/MlVhPWDT9TWiqdDpfAOUb0o7gipFQzLog=
env:
  global:
    secure: fr1HaMoEs+lXPL5gtg1mOFHM8kl9IImrr9sVunY3G5PVq1wjgkhF20WSbCARONJb2L6Yw1jbz77zfiA7vhipFhAvFax7wMCvoqWjbxnOKiEQv9+yYis+8YyBnomicnPBSpIOAE0RE7D+yqPSth4I0z+zje/+IvYnt7LxPbBSlLdvbYPzpGWgY3Yaq9H1RCMOX3w0vpQuqBGu3kNMX2iPBeb/kdeiOgwvJR5yHIxTavoeCsqhT1phkwdlKMiykhMYiH2hqnu3SNH3FJA5mp13X1sez086F9tfVD4yz4RMzORs4zucMnF9m7b19kF4tI/0gufTmfNKUy1pyIzJZ9frPw9YpsAMNiZGHSdS5Lp/RJs/5zeh3V0hmYzOvJjTaIm6UGT56o5rMXZ/WiHc6JI1gcGUrFo+oV4atRavg9gWsjJm2dPtYJ8KmiXPg16EjIrsAIhNdaMqbbbtuy3ANEkXsyiS9keT9nLDxoItGpJtfjvASqx7tpdFB556qOPTtyifuBM9ELalC6/ZfSy53O84XVVkGqMQValbhngSAmaHvR+JNMnYfxto8zfcrixNvnpVy8UPpY6cjdnFrGOh1HzH32AlhUl/9J+skmD0QAF5h76BnQzej77QlKLtr1fN9Z/UZ5uuGsvSfIqc9ZBhUO5TQZK1DQASYO0r/YtPux0shg8=
